using SDHP.Entities.CommonEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SDHP.Repository.Migrations
{
    internal sealed partial class Configuration
    {
        #region [ City ]
        public _CityLookup[] City = new _CityLookup[]
        {
            new _CityLookup() { DistrictID=1,CityName = "TestCity1" , Hide = false },
             new _CityLookup() {DistrictID=2,CityName = "TestCity2" , Hide = false },
        };
        #endregion
        #region [ District ]
        public _DistrictLookup[] District = new _DistrictLookup[]
        {
            new _DistrictLookup() { StateID=1,DistrictName = "TestDistrict1" , Hide = false },
            new _DistrictLookup() { StateID=1,DistrictName = "TestDistrict2" , Hide = false },
        };
        #endregion
        #region [ States ]
        public _StateLookup[] States = new _StateLookup[]
        {
          new _StateLookup() { CountryID=25,StateName = "Acre", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Alagoas" , Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Amapá", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Amazonas", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Bahía", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Ceará", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Distrito Federal", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Espirito Santo", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Goiás", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Maranhão", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Mato Grosso", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Mato Grosso do Sul", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Minas Geraís", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Pará", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Paraíba", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Paraná", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Pernambuco", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Piauí", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Rio de Janeiro", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Rio Grande do Norte", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Rio Grande do Sul", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Rondônia", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Roraima", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Santa Catarina", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "São Paulo", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Sergipe", Hide = false },
          new _StateLookup() { CountryID=25,StateName = "Tocantins", Hide = false },
        };
        #endregion
        #region [ Countries ]
        public _CountryLookup[] Counties = new _CountryLookup[]
        {
            new _CountryLookup() { CountryName = "Afghanistan" , Hide = false },
            new _CountryLookup() { CountryName = "Albania", Hide = false },
            new _CountryLookup() { CountryName = "Algeria", Hide = false },
            new _CountryLookup() { CountryName = "Andorra", Hide = false },
            new _CountryLookup() { CountryName = "Angola", Hide = false },
            new _CountryLookup() { CountryName = "Antigua and Barbuda", Hide = false },
            new _CountryLookup() { CountryName = "Argentina", Hide = false },
            new _CountryLookup() { CountryName = "Armenia", Hide = false },
            new _CountryLookup() { CountryName = "Aruba", Hide = false },
            new _CountryLookup() { CountryName = "Australia", Hide = false },
            new _CountryLookup() { CountryName = "Austria", Hide = false },
            new _CountryLookup() { CountryName = "Azerbaijan", Hide = false },
            new _CountryLookup() { CountryName = "Bahamas, The", Hide = false },
            new _CountryLookup() { CountryName = "Bahrain", Hide = false },
            new _CountryLookup() { CountryName = "Bangladesh", Hide = false },
            new _CountryLookup() { CountryName = "Barbados", Hide = false },
            new _CountryLookup() { CountryName = "Belarus", Hide = false },
            new _CountryLookup() { CountryName = "Belgium", Hide = false },
            new _CountryLookup() { CountryName = "Belize", Hide = false },
            new _CountryLookup() { CountryName = "Benin", Hide = false },
            new _CountryLookup() { CountryName = "Bhutan", Hide = false },
            new _CountryLookup() { CountryName = "Bolivia", Hide = false },
            new _CountryLookup() { CountryName = "Bosnia and Herzegovina", Hide = false },
            new _CountryLookup() { CountryName = "Botswana", Hide = false },
            new _CountryLookup() { CountryName = "Brazil", Hide = false },
            new _CountryLookup() { CountryName = "Brunei", Hide = false },
            new _CountryLookup() { CountryName = "Bulgaria", Hide = false },
            new _CountryLookup() { CountryName = "Burkina Faso", Hide = false },
            new _CountryLookup() { CountryName = "Burma", Hide = false },
            new _CountryLookup() { CountryName = "Burundi", Hide = false },
            new _CountryLookup() { CountryName = "Cambodia", Hide = false },
            new _CountryLookup() { CountryName = "Cameroon", Hide = false },
            new _CountryLookup() { CountryName = "Canada", Hide = false },
            new _CountryLookup() { CountryName = "Cabo Verde", Hide = false },
            new _CountryLookup() { CountryName = "Central African Republic", Hide = false },
            new _CountryLookup() { CountryName = "Chad", Hide = false },
            new _CountryLookup() { CountryName = "Chile", Hide = false },
            new _CountryLookup() { CountryName = "China", Hide = false },
            new _CountryLookup() { CountryName = "Colombia", Hide = false },
            new _CountryLookup() { CountryName = "Comoros", Hide = false },
            new _CountryLookup() { CountryName = "Congo, Democratic Republic of the", Hide = false },
            new _CountryLookup() { CountryName = "Congo, Republic of the", Hide = false },
            new _CountryLookup() { CountryName = "Costa Rica", Hide = false },
            new _CountryLookup() { CountryName = "Cote d'Ivoire", Hide = false },
            new _CountryLookup() { CountryName = "Croatia", Hide = false },
            new _CountryLookup() { CountryName = "Cuba", Hide = false },
            new _CountryLookup() { CountryName = "Curacao", Hide = false },
            new _CountryLookup() { CountryName = "Cyprus", Hide = false },
            new _CountryLookup() { CountryName = "Czechia", Hide = false },
            new _CountryLookup() { CountryName = "Denmark", Hide = false },
            new _CountryLookup() { CountryName = "Djibouti", Hide = false },
            new _CountryLookup() { CountryName = "Dominica", Hide = false },
            new _CountryLookup() { CountryName = "Dominican Republic", Hide = false },
            new _CountryLookup() { CountryName = "East Timor (see Timor-Leste)", Hide = false },
            new _CountryLookup() { CountryName = "Ecuador", Hide = false },
            new _CountryLookup() { CountryName = "Egypt", Hide = false },
            new _CountryLookup() { CountryName = "El Salvador", Hide = false },
            new _CountryLookup() { CountryName = "Equatorial Guinea", Hide = false },
            new _CountryLookup() { CountryName = "Eritrea", Hide = false },
            new _CountryLookup() { CountryName = "Estonia", Hide = false },
            new _CountryLookup() { CountryName = "Ethiopia", Hide = false },
            new _CountryLookup() { CountryName = "Fiji", Hide = false },
            new _CountryLookup() { CountryName = "Finland", Hide = false },
            new _CountryLookup() { CountryName = "France", Hide = false },
            new _CountryLookup() { CountryName = "Gabon", Hide = false },
            new _CountryLookup() { CountryName = "Gambia, The", Hide = false },
            new _CountryLookup() { CountryName = "Georgia", Hide = false },
            new _CountryLookup() { CountryName = "Germany", Hide = false },
            new _CountryLookup() { CountryName = "Ghana", Hide = false },
            new _CountryLookup() { CountryName = "Greece", Hide = false },
            new _CountryLookup() { CountryName = "Grenada", Hide = false },
            new _CountryLookup() { CountryName = "Guatemala", Hide = false },
            new _CountryLookup() { CountryName = "Guinea", Hide = false },
            new _CountryLookup() { CountryName = "Guinea-Bissau", Hide = false },
            new _CountryLookup() { CountryName = "Guyana", Hide = false },
            new _CountryLookup() { CountryName = "Haiti", Hide = false },
            new _CountryLookup() { CountryName = "Holy See", Hide = false },
            new _CountryLookup() { CountryName = "Honduras", Hide = false },
            new _CountryLookup() { CountryName = "Hong Kong", Hide = false },
            new _CountryLookup() { CountryName = "Hungary", Hide = false },
            new _CountryLookup() { CountryName = "Iceland", Hide = false },
            new _CountryLookup() { CountryName = "India", Hide = false },
            new _CountryLookup() { CountryName = "Indonesia", Hide = false },
            new _CountryLookup() { CountryName = "Iran", Hide = false },
            new _CountryLookup() { CountryName = "Iraq", Hide = false },
            new _CountryLookup() { CountryName = "Ireland", Hide = false },
            new _CountryLookup() { CountryName = "Israel", Hide = false },
            new _CountryLookup() { CountryName = "Italy", Hide = false },
            new _CountryLookup() { CountryName = "Jamaica", Hide = false },
            new _CountryLookup() { CountryName = "Japan", Hide = false },
            new _CountryLookup() { CountryName = "Jordan", Hide = false },
            new _CountryLookup() { CountryName = "Kazakhstan", Hide = false },
            new _CountryLookup() { CountryName = "Kenya", Hide = false },
            new _CountryLookup() { CountryName = "Kiribati", Hide = false },
            new _CountryLookup() { CountryName = "Korea, North", Hide = false },
            new _CountryLookup() { CountryName = "Korea, South", Hide = false },
            new _CountryLookup() { CountryName = "Kosovo", Hide = false },
            new _CountryLookup() { CountryName = "Kuwait", Hide = false },
            new _CountryLookup() { CountryName = "Kyrgyzstan", Hide = false },
            new _CountryLookup() { CountryName = "Laos", Hide = false },
            new _CountryLookup() { CountryName = "Latvia", Hide = false },
            new _CountryLookup() { CountryName = "Lebanon", Hide = false },
            new _CountryLookup() { CountryName = "Lesotho", Hide = false },
            new _CountryLookup() { CountryName = "Liberia", Hide = false },
            new _CountryLookup() { CountryName = "Libya", Hide = false },
            new _CountryLookup() { CountryName = "Liechtenstein", Hide = false },
            new _CountryLookup() { CountryName = "Lithuania", Hide = false },
            new _CountryLookup() { CountryName = "Luxembourg", Hide = false },
            new _CountryLookup() { CountryName = "Macau", Hide = false },
            new _CountryLookup() { CountryName = "Macedonia", Hide = false },
            new _CountryLookup() { CountryName = "Madagascar", Hide = false },
            new _CountryLookup() { CountryName = "Malawi", Hide = false },
            new _CountryLookup() { CountryName = "Malaysia", Hide = false },
            new _CountryLookup() { CountryName = "Maldives", Hide = false },
            new _CountryLookup() { CountryName = "Mali", Hide = false },
            new _CountryLookup() { CountryName = "Malta", Hide = false },
            new _CountryLookup() { CountryName = "Marshall Islands", Hide = false },
            new _CountryLookup() { CountryName = "Mauritania", Hide = false },
            new _CountryLookup() { CountryName = "Mauritius", Hide = false },
            new _CountryLookup() { CountryName = "Mexico", Hide = false },
            new _CountryLookup() { CountryName = "Micronesia", Hide = false },
            new _CountryLookup() { CountryName = "Moldova", Hide = false },
            new _CountryLookup() { CountryName = "Monaco", Hide = false },
            new _CountryLookup() { CountryName = "Mongolia", Hide = false },
            new _CountryLookup() { CountryName = "Montenegro", Hide = false },
            new _CountryLookup() { CountryName = "Morocco", Hide = false },
            new _CountryLookup() { CountryName = "Mozambique", Hide = false },
            new _CountryLookup() { CountryName = "Namibia", Hide = false },
            new _CountryLookup() { CountryName = "Nauru", Hide = false },
            new _CountryLookup() { CountryName = "Nepal", Hide = false },
            new _CountryLookup() { CountryName = "Netherlands", Hide = false },
            new _CountryLookup() { CountryName = "New Zealand", Hide = false },
            new _CountryLookup() { CountryName = "Nicaragua", Hide = false },
            new _CountryLookup() { CountryName = "Niger", Hide = false },
            new _CountryLookup() { CountryName = "Nigeria", Hide = false },
            new _CountryLookup() { CountryName = "North Korea", Hide = false },
            new _CountryLookup() { CountryName = "Norway", Hide = false },
            new _CountryLookup() { CountryName = "Oman", Hide = false },
            new _CountryLookup() { CountryName = "Pakistan", Hide = false },
            new _CountryLookup() { CountryName = "Palau", Hide = false },
            new _CountryLookup() { CountryName = "Palestinian Territories", Hide = false },
            new _CountryLookup() { CountryName = "Panama", Hide = false },
            new _CountryLookup() { CountryName = "Papua New Guinea", Hide = false },
            new _CountryLookup() { CountryName = "Paraguay", Hide = false },
            new _CountryLookup() { CountryName = "Peru", Hide = false },
            new _CountryLookup() { CountryName = "Philippines", Hide = false },
            new _CountryLookup() { CountryName = "Poland", Hide = false },
            new _CountryLookup() { CountryName = "Portugal", Hide = false },
            new _CountryLookup() { CountryName = "Qatar", Hide = false },
            new _CountryLookup() { CountryName = "Romania", Hide = false },
            new _CountryLookup() { CountryName = "Russia", Hide = false },
            new _CountryLookup() { CountryName = "Rwanda", Hide = false },
            new _CountryLookup() { CountryName = "Saint Kitts and Nevis", Hide = false },
            new _CountryLookup() { CountryName = "Saint Lucia", Hide = false },
            new _CountryLookup() { CountryName = "Saint Vincent and the Grenadines", Hide = false },
            new _CountryLookup() { CountryName = "Samoa", Hide = false },
            new _CountryLookup() { CountryName = "San Marino", Hide = false },
            new _CountryLookup() { CountryName = "Sao Tome and Principe", Hide = false },
            new _CountryLookup() { CountryName = "Saudi Arabia", Hide = false },
            new _CountryLookup() { CountryName = "Senegal", Hide = false },
            new _CountryLookup() { CountryName = "Serbia", Hide = false },
            new _CountryLookup() { CountryName = "Seychelles", Hide = false },
            new _CountryLookup() { CountryName = "Sierra Leone", Hide = false },
            new _CountryLookup() { CountryName = "Singapore", Hide = false },
            new _CountryLookup() { CountryName = "Sint Maarten", Hide = false },
            new _CountryLookup() { CountryName = "Slovakia", Hide = false },
            new _CountryLookup() { CountryName = "Slovenia", Hide = false },
            new _CountryLookup() { CountryName = "Solomon Islands", Hide = false },
            new _CountryLookup() { CountryName = "Somalia", Hide = false },
            new _CountryLookup() { CountryName = "South Africa", Hide = false },
            new _CountryLookup() { CountryName = "South Korea", Hide = false },
            new _CountryLookup() { CountryName = "South Sudan", Hide = false },
            new _CountryLookup() { CountryName = "Spain", Hide = false },
            new _CountryLookup() { CountryName = "Sri Lanka", Hide = false },
            new _CountryLookup() { CountryName = "Sudan", Hide = false },
            new _CountryLookup() { CountryName = "Suriname", Hide = false },
            new _CountryLookup() { CountryName = "Swaziland", Hide = false },
            new _CountryLookup() { CountryName = "Sweden", Hide = false },
            new _CountryLookup() { CountryName = "Switzerland", Hide = false },
            new _CountryLookup() { CountryName = "Syria", Hide = false },
            new _CountryLookup() { CountryName = "Taiwan", Hide = false },
            new _CountryLookup() { CountryName = "Tajikistan", Hide = false },
            new _CountryLookup() { CountryName = "Tanzania", Hide = false },
            new _CountryLookup() { CountryName = "Thailand", Hide = false },
            new _CountryLookup() { CountryName = "Timor-Leste", Hide = false },
            new _CountryLookup() { CountryName = "Togo", Hide = false },
            new _CountryLookup() { CountryName = "Tonga", Hide = false },
            new _CountryLookup() { CountryName = "Trinidad and Tobago", Hide = false },
            new _CountryLookup() { CountryName = "Tunisia", Hide = false },
            new _CountryLookup() { CountryName = "Turkey", Hide = false },
            new _CountryLookup() { CountryName = "Turkmenistan", Hide = false },
            new _CountryLookup() { CountryName = "Tuvalu", Hide = false },
            new _CountryLookup() { CountryName = "Uganda", Hide = false },
            new _CountryLookup() { CountryName = "Ukraine", Hide = false },
            new _CountryLookup() { CountryName = "United Arab Emirates", Hide = false },
            new _CountryLookup() { CountryName = "United Kingdom", Hide = false },
            new _CountryLookup() { CountryName = "United States of America", Hide = false },
            new _CountryLookup() { CountryName = "Uruguay", Hide = false },
            new _CountryLookup() { CountryName = "Uzbekistan", Hide = false },
            new _CountryLookup() { CountryName = "Vanuatu", Hide = false },
            new _CountryLookup() { CountryName = "Venezuela", Hide = false },
            new _CountryLookup() { CountryName = "Vietnam", Hide = false },
            new _CountryLookup() { CountryName = "Yemen", Hide = false },
            new _CountryLookup() { CountryName = "Zambia", Hide = false },
            new _CountryLookup() { CountryName = "Zimbabwe", Hide = false }
        };
        #endregion   

    }
}
